//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsrInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUsrInfo()
        {
            this.tblUsrDetails = new HashSet<tblUsrDetail>();
        }
    
        public int UsrInfoID { get; set; }
        public string UsrName { get; set; }
        public string UsrPass { get; set; }
        public bool UsrIsLog { get; set; }
        public bool UsrStatus { get; set; }
        public Nullable<System.DateTime> UsrLastLog { get; set; }
        public byte UsrLoginAttempt { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UsrGroupID { get; set; }
        public string UsrModuleAccess { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string photoLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsrDetail> tblUsrDetails { get; set; }
    }
}
