//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_POHeaderShort
    {
        public decimal PO_No { get; set; }
        public string PO_Stat { get; set; }
        public string PO_Status_Des { get; set; }
        public decimal PO_Vendor_No { get; set; }
        public string PO_Vendor_Name { get; set; }
        public string PO_Entry_Date { get; set; }
        public decimal PO_Cost { get; set; }
        public decimal PO_SKU_Level_Allowance { get; set; }
        public decimal PO_Vendor_Level_Allowance { get; set; }
        public string PO_Buyer_Init { get; set; }
        public string PO_Buyer_Name { get; set; }
    }
}
